//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernUIForWPFSample.WithoutBackButton
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        public Accessory()
        {
            this.PurchaseAccessories = new HashSet<PurchaseAccessory>();
        }
    
        public int ID { get; set; }
        public string AccID { get; set; }
        public string Category { get; set; }
        public string UnitType { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
        public Nullable<float> NoOfUnits { get; set; }
        public Nullable<decimal> TransportCost { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ICollection<PurchaseAccessory> PurchaseAccessories { get; set; }
    }
}
