//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernUIForWPFSample.WithoutBackButton
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualCost
    {
        public ActualCost()
        {
            this.AccessoryCosts = new HashSet<AccessoryCost>();
            this.StockInHands = new HashSet<StockInHand>();
        }
    
        public int ID { get; set; }
        public string ACostID { get; set; }
        public string CM { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    
        public virtual ICollection<AccessoryCost> AccessoryCosts { get; set; }
        public virtual ICollection<StockInHand> StockInHands { get; set; }
    }
}
