//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernUIForWPFSample.WithoutBackButton
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class adoraDBContext : DbContext
    {
        public adoraDBContext()
            : base("name=adoraDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessory> Accessories { get; set; }
        public virtual DbSet<AccessoryCost> AccessoryCosts { get; set; }
        public virtual DbSet<ActualCost> ActualCosts { get; set; }
        public virtual DbSet<BnSFrequency> BnSFrequencies { get; set; }
        public virtual DbSet<CurCategory> CurCategories { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Fabric> Fabrics { get; set; }
        public virtual DbSet<FabricCost> FabricCosts { get; set; }
        public virtual DbSet<FixedOverhead> FixedOverheads { get; set; }
        public virtual DbSet<FOBSalesFrequency> FOBSalesFrequencies { get; set; }
        public virtual DbSet<FOBSalesShipment> FOBSalesShipments { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<ManageCurrency> ManageCurrencies { get; set; }
        public virtual DbSet<ManageFix> ManageFixes { get; set; }
        public virtual DbSet<ManageFOBSalesShipment> ManageFOBSalesShipments { get; set; }
        public virtual DbSet<ManagePSDetail> ManagePSDetails { get; set; }
        public virtual DbSet<ManageStock> ManageStocks { get; set; }
        public virtual DbSet<PurchaseAccessory> PurchaseAccessories { get; set; }
        public virtual DbSet<PurchaseFab> PurchaseFabs { get; set; }
        public virtual DbSet<PurchasingShipment> PurchasingShipments { get; set; }
        public virtual DbSet<StockInHand> StockInHands { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<showBnSDetail> showBnSDetails { get; set; }
        public virtual DbSet<showCurDetail> showCurDetails { get; set; }
    }
}
