//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernUIForWPFSample.WithoutBackButton
{
    using System;
    using System.Collections.Generic;
    
    public partial class BnSFrequency
    {
        public string ShipmentID { get; set; }
        public int FrequencyID { get; set; }
        public Nullable<int> NoOfPieces { get; set; }
        public Nullable<decimal> PricePerPiece { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual PurchasingShipment PurchasingShipment { get; set; }
    }
}
