//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernUIForWPFSample.WithoutBackButton
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurCategory
    {
        public CurCategory()
        {
            this.Currencies = new HashSet<Currency>();
        }
    
        public int ID { get; set; }
        public string CurCatID { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<Currency> Currencies { get; set; }
    }
}
