//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernUIForWPFSample.WithoutBackButton
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.ManageCurrencies = new HashSet<ManageCurrency>();
        }
    
        public int ID { get; set; }
        public string CurrencyID { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string CurrencyCategory { get; set; }
        public Nullable<System.DateTime> change { get; set; }
    
        public virtual CurCategory CurCategory { get; set; }
        public virtual ICollection<ManageCurrency> ManageCurrencies { get; set; }
    }
}
