//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernUIForWPFSample.WithoutBackButton
{
    using System;
    using System.Collections.Generic;
    
    public partial class FabricCost
    {
        public int ID { get; set; }
        public string FabCostID { get; set; }
        public string Type { get; set; }
        public Nullable<float> Amount { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string ACostID { get; set; }
        public Nullable<float> costPyard { get; set; }
    }
}
