//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernUIForWPFSample.WithoutBackButton
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fabric
    {
        public Fabric()
        {
            this.PurchaseFabs = new HashSet<PurchaseFab>();
        }
    
        public int ID { get; set; }
        public string FabID { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> PricePerYard { get; set; }
        public Nullable<float> Yardage { get; set; }
        public Nullable<decimal> TransportCost { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ICollection<PurchaseFab> PurchaseFabs { get; set; }
    }
}
