//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernUIForWPFSample.WithoutBackButton
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedOverhead
    {
        public FixedOverhead()
        {
            this.ManageFixes = new HashSet<ManageFix>();
        }
    
        public int ID { get; set; }
        public string FixID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<decimal> Electricity { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Water { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> RentOrMortgage { get; set; }
        public Nullable<decimal> PhoneAnInternet { get; set; }
        public Nullable<decimal> Fuel { get; set; }
        public Nullable<decimal> Misc { get; set; }
        public Nullable<decimal> Ot { get; set; }
        public Nullable<decimal> Other { get; set; }
    
        public virtual ICollection<ManageFix> ManageFixes { get; set; }
    }
}
