//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernUIForWPFSample.WithoutBackButton
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageFix
    {
        public string UserName { get; set; }
        public string FixID { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    
        public virtual FixedOverhead FixedOverhead { get; set; }
        public virtual User User { get; set; }
    }
}
