//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernUIForWPFSample.WithoutBackButton
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasingShipment
    {
        public PurchasingShipment()
        {
            this.BnSFrequencies = new HashSet<BnSFrequency>();
            this.ManagePSDetails = new HashSet<ManagePSDetail>();
        }
    
        public int ID { get; set; }
        public string ShipmentID { get; set; }
        public string Title { get; set; }
        public Nullable<int> NoOfPieces { get; set; }
        public Nullable<decimal> PricePerPiece { get; set; }
        public Nullable<decimal> ActualCostPerPiece { get; set; }
        public Nullable<decimal> Micelleneous { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> TransportCost { get; set; }
        public Nullable<decimal> SupplierCommission { get; set; }
    
        public virtual ICollection<BnSFrequency> BnSFrequencies { get; set; }
        public virtual ICollection<ManagePSDetail> ManagePSDetails { get; set; }
    }
}
