//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernUIForWPFSample.WithoutBackButton
{
    using System;
    using System.Collections.Generic;
    
    public partial class showBnSDetail
    {
        public string Shipment_Name { get; set; }
        public System.DateTime Frequency_Date { get; set; }
        public int Frequency_No { get; set; }
        public Nullable<int> Number_of_Pieces { get; set; }
        public Nullable<decimal> Price_per_piece { get; set; }
        public Nullable<decimal> Total_Gross { get; set; }
    }
}
