//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernUIForWPFSample.WithoutBackButton
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInHand
    {
        public StockInHand()
        {
            this.FOBSalesFrequencies = new HashSet<FOBSalesFrequency>();
            this.Images = new HashSet<Image>();
            this.ManageStocks = new HashSet<ManageStock>();
        }
    
        public int ID { get; set; }
        public string StockID { get; set; }
        public string FactoryName { get; set; }
        public string ItemName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ACostID { get; set; }
        public Nullable<int> NoOfItems { get; set; }
        public string descript { get; set; }
    
        public virtual ActualCost ActualCost { get; set; }
        public virtual ICollection<FOBSalesFrequency> FOBSalesFrequencies { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<ManageStock> ManageStocks { get; set; }
    }
}
