//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernUIForWPFSample.WithoutBackButton
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ManageCurrencies = new HashSet<ManageCurrency>();
            this.ManageFixes = new HashSet<ManageFix>();
            this.ManageFOBSalesShipments = new HashSet<ManageFOBSalesShipment>();
            this.ManagePSDetails = new HashSet<ManagePSDetail>();
            this.ManageStocks = new HashSet<ManageStock>();
            this.PurchaseAccessories = new HashSet<PurchaseAccessory>();
            this.PurchaseFabs = new HashSet<PurchaseFab>();
        }
    
        public string UserName { get; set; }
        public string password { get; set; }
        public string NIC { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<ManageCurrency> ManageCurrencies { get; set; }
        public virtual ICollection<ManageFix> ManageFixes { get; set; }
        public virtual ICollection<ManageFOBSalesShipment> ManageFOBSalesShipments { get; set; }
        public virtual ICollection<ManagePSDetail> ManagePSDetails { get; set; }
        public virtual ICollection<ManageStock> ManageStocks { get; set; }
        public virtual ICollection<PurchaseAccessory> PurchaseAccessories { get; set; }
        public virtual ICollection<PurchaseFab> PurchaseFabs { get; set; }
    }
}
